apiVersion: v1
kind: ConfigMap
metadata:
  name: aws-auth
  namespace: kube-system
data:
  mapRoles: |
    - rolearn: arn:aws:iam::482720962971:role/eks-cluster-nodes
      username: system:node:{{EC2PrivateDNSName}}
      groups:
        - system:bootstrappers
        - system:nodes
  mapUsers: |
    - userarn: arn:aws:iam::482720962971:user/JenkinsServiceUser
      username: JenkinsServiceUser 
      groups:
        - system:masters
    - userarn: arn:aws:iam::482720962971:user/dmdemchuk
      username: dmdemchuk
      groups:
        - system:masters