apiVersion: apps/v1
kind: Deployment
metadata: 
  name: hello-world
  namespace: {{ $.Values.Namespace }}
spec: 
  replicas: {{ $.Values.replicaCount }}
  selector:
    matchLabels:
      component: web
  template:
    metadata:
      labels:
       component: web
    spec:
      containers:
        - name: nginx
          image: 131460758684.dkr.ecr.us-west-2.amazonaws.com/nginxtest:{{ $.Values.biuldNumber }}
          ports:
            - containerPort: 80